version: "2"

services:
  test:
    image: tuleap-run-e2e-tests-v2
    build:
      context: ./tests/e2e/docker
      dockerfile: run-tests.dockerfile
      args:
        DOCKER_REGISTRY: ${DOCKER_REGISTRY:-docker.io}
        CYPRESS_VERSION: $CYPRESS_VERSION
    command: /tuleap/tests/e2e/full/run.sh
    shm_size: 512M
    volumes:
      - .:/tuleap
      - ${TEST_RESULT_OUTPUT}:/output
    networks:
      - tuleap
      - external-connectivity

  tuleap:
    image: ${DOCKER_REGISTRY:-docker.io}/tuleap/tuleap-community-edition:latest
    entrypoint: /usr/share/tuleap/tests/e2e/full/tuleap/setup.sh
    environment:
      - TULEAP_FQDN=tuleap
      - DB_HOST=db
      - DB_ADMIN_USER=root
      - DB_ADMIN_PASSWORD=welcome0
    volumes:
      - .:/usr/share/tuleap:ro
    networks:
      - tuleap
    depends_on:
      - mysql57

  mysql57:
    image: ${DOCKER_REGISTRY:-docker.io}/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=welcome0
    volumes:
      - ./tests/etc/DBConfig/mysql-server.cnf:/etc/mysql/mysql.conf.d/mysql-server.cnf:ro,cached
    tmpfs: /tmp
    networks:
      - tuleap

networks:
  tuleap:
    internal: true
  external-connectivity:
