packages:  # all packages in subdirs of packages/ and components/  - 'packages/**'
  - "lib/frontend/**/"
  - "src/scripts/tlp-doc"
  - "src/"
  - "src/themes/tlp"
  - "src/themes/BurningParrot"
  - "plugins/**/"
shared-workspace-lockfile: false
