# Angular
[[IgnoredVulns]]
id = "GHSA-m2h2-264f-f486" # CVE-2022-25844
reason = "Angular is EOL. Nothing in the codebase can trigger this ReDoS issue."

[[IgnoredVulns]]
id = "GHSA-prc3-vjfx-vhm9" # CVE-2022-25869
reason = "Angular is EOL. XSS can only be trigerred with IE. IE users would not be able to load the JS of Angular app in Tuleap."

[[IgnoredVulns]]
id = "GHSA-2qqx-w9hr-q5gx" # CVE-2023-26117
reason = "Angular is EOL. Nothing in the codebase can trigger this ReDoS issue."

[[IgnoredVulns]]
id = "GHSA-2vrf-hf26-jrp5" # CVE-2023-26116
reason = "Angular is EOL. Nothing in the codebase can trigger this ReDoS issue."

[[IgnoredVulns]]
id = "GHSA-qwqh-hm9m-p5hr" # CVE-2023-26118
reason = "Angular is EOL. Nothing in the codebase can trigger this ReDoS issue."

# src/additional-packages/wasmtime-wrapper-lib/Cargo.lock
## atty
[[IgnoredVulns]]
id = "RUSTSEC-2021-0145"
reason = "Windows only."

## mach
[[IgnoredVulns]]
id = "RUSTSEC-2020-0168"
reason = "Only used when targetting macOS."

### TO BE FIXED

# Dev tools
## minimatch
[[IgnoredVulns]]
id = "GHSA-f8q6-p94x-37v3" # CVE-2022-3517
reason = "ReDoS. Only used as a dev tool."
ignoreUntil = 2023-05-08

## minimist
[[IgnoredVulns]]
id = "GHSA-xvch-5gv4-984h" # CVE-2021-44906
reason = "Not exploitable. Only used as a dev tool."
ignoreUntil = 2023-05-08

## async
[[IgnoredVulns]]
id = "GHSA-fwr7-v2mv-hh25" # CVE-2021-43138
reason = "Not exploitable. Only used as a dev tool."
ignoreUntil = 2023-05-08

## qs
[[IgnoredVulns]]
id = "GHSA-hrpp-h998-j3pp" # CVE-2022-24999
reason = "Not exploitable. Only used as a dev tool."
ignoreUntil = 2023-05-08

[[IgnoredVulns]]
id = "GHSA-mc8h-8q98-g5hr" # RUSTSEC-2023-0018
reason = "Only used at build time."
ignoreUntil = 2023-05-08

## nth-check
[[IgnoredVulns]]
id = "GHSA-rp65-9cf3-cjxr" # CVE-2021-3803
reason = "ReDoS. To be investigated."
ignoreUntil = 2023-05-08

# plugins/mediawiki_standalone/additional-packages/mediawiki-mathoid/pnpm-lock.yaml
## jsdom
[[IgnoredVulns]]
id = "GHSA-f4c9-cqv8-9v98" # CVE-2021-20066
reason = "To be investigated/reported upstream."
ignoreUntil = 2023-05-08

## ms
[[IgnoredVulns]]
id = "GHSA-w9mr-4mfr-499f" # CVE-2017-20162
reason = "ReDoS. To be investigated/reported upstream/ignored."
ignoreUntil = 2023-05-08

## requestretry
[[IgnoredVulns]]
id = "GHSA-hjp8-2cm3-cc45" # CVE-2022-0654
reason = "No external call in our setup. To be investigated/reported upstream/ignored."
ignoreUntil = 2023-05-08

## request
[[IgnoredVulns]]
id = "GHSA-p8p7-x288-28g6" # CVE-2023-28155
reason = "No outbound HTTP request in our situation. To be investigated/reported upstream/ignored."
ignoreUntil = 2023-05-08

# src/additional-packages/tuleap-realtime/pnpm-lock.yaml
## simple-get
[[IgnoredVulns]]
id = "GHSA-wpg7-2c88-r8xv" # CVE-2022-0355
reason = "To be investigated."
ignoreUntil = 2023-05-08
