[package]
name = "wasmtimewrapper"
version = "0.2.0"
edition = "2021"

[lib]
name = "wasmtimewrapper"
path = "src/lib.rs"
crate-type = ["cdylib"]

[build-dependencies]
cbindgen = "0.24.3"

[dependencies]
async-trait = "0.1"
cap-std = "1.0.15"
rustix = "0.37.19"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
anyhow = "1.0.66"
wasmtime = { version = "10.0.0", default_features = false, features = ["parallel-compilation", "cranelift", "pooling-allocator"] }
wasmtime-wasi = "10.0.0"
wasi-common = "10.0.0"